name: MySillyDreams CI/CD

on:
  push:
    paths:
      - 'src/main/java/**/*.java' # Assuming Java files for the Spring Boot app are under src/main/java
      - 'app/src/**/*'             # Assuming Android app source files are under app/src
      - 'ios/**/*'                 # Assuming iOS app source files are under ios
  pull_request:
    paths:
      - 'src/main/java/**/*.java'
      - 'app/src/**/*'
      - 'ios/**/*'

jobs:
  build_web:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && (contains(github.event.head_commit.added, 'src/main/java/') || contains(github.event.head_commit.modified, 'src/main/java/')) ||
             github.event_name == 'pull_request' && (contains(github.event.pull_request.head.repo.full_name, github.repository) && (contains(github.event.pull_request.base.ref, 'main') || contains(github.event.pull_request.base.ref, 'master'))) }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permissions to gradlew
      run: chmod +x gradlew

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle
      run: ./gradlew build --no-daemon


  build_android:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && (contains(github.event.head_commit.added, 'app/src/') || contains(github.event.head_commit.modified, 'app/src/')) ||
             github.event_name == 'pull_request' && (contains(github.event.pull_request.head.repo.full_name, github.repository) && (contains(github.event.pull_request.base.ref, 'main') || contains(github.event.pull_request.base.ref, 'master'))) }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Set up Android SDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permissions to gradlew
      run: chmod +x gradlew

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle
      run: ./gradlew build --no-daemon

  build_ios:
    runs-on: macos-latest
    if: ${{ github.event_name == 'push' && (contains(github.event.head_commit.added, 'ios/') || contains(github.event.head_commit.modified, 'ios/')) ||
             github.event_name == 'pull_request' && (contains(github.event.pull_request.head.repo.full_name, github.repository) && (contains(github.event.pull_request.base.ref, 'main') || contains(github.event.pull_request.base.ref, 'master'))) }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permissions to gradlew
      run: chmod +x gradlew

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle
      run: ./gradlew build --no-daemon

