name: Web Application CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permissions to gradlew
        run: chmod +x gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      # Docker build and push

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/userapi-image .
      - name: Publish image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/userapi-image:latest

  deploy:
    needs: build
    runs-on: hyd-ap-south-2c
    steps:
      - name: Pull Image from docker hub
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/userapi-image:latest
      - name: Delete old container
        run: sudo docker rm -f springboot-eventmangement-container
      - name: Run ./run.sh in background
        run: sudo ./run.sh &
      - name: Run docker container
        run: sudo docker run -d -p 80:80 --name springboot-eventmangement-container ${{ secrets.DOCKER_USERNAME }}/userapi-image:latest
