name: Web Application CI/CD

on:
  push:
    paths:
      - 'src/main/java/**/*.java'
  pull_request:
    paths:
      - 'src/main/java/**/*.java'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && (contains(github.event.head_commit.added, 'src/main/java/') || contains(github.event.head_commit.modified, 'src/main/java/')) ||
      github.event_name == 'pull_request' && (contains(github.event.pull_request.head.repo.full_name, github.repository) && (contains(github.event.pull_request.base.ref, 'main') || contains(github.event.pull_request.base.ref, 'master'))) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permissions to gradlew
        run: chmod +x gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

        # Docker build and push
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/userapi-image .
      - name: Publish image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/userapi-image:latest

  deploy:
    needs: build
    runs-on: hyd-ap-south-2c
    steps:
      - name: Pull Image from docker hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/userapi-image:latest
      - name: Delete old container
        run: docker rm -f springboot-eventmangement-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name springboot-eventmangement-container ${{ secrets.DOCKER_USERNAME }}/userapi-image:latest

