name: Web Application CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permissions to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      # Check if PostgreSQL client is installed
      - name: Check PostgreSQL client installation
        id: check_postgresql
        run: |
          if dpkg -s postgresql-client &> /dev/null; then
            echo "::set-output name=installed::true"
          else
            echo "::set-output name=installed::false"
          fi

      # Install PostgreSQL client if not already installed
      - name: Install PostgreSQL Client
        if: ${{ steps.check_postgresql.outputs.installed != 'true' }}
        run: |
          sudo apt-get update
          sudo apt-get install postgresql-client -y

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Wait for PostgreSQL to start
        run: docker-compose up -d my-userapi-app postgres && sleep 15

      - name: Set up PostgreSQL Client
        env:
          PGPASSWORD: Praveen@663
        run: |
          psql -h localhost -U postgres -d EventMaster -c "SELECT version();"

      - name: Build Docker images
        run: |
          docker-compose build

      - name: Push Docker images to Docker Hub
        run: |
          docker-compose push

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Images from Docker Hub
        run: docker-compose pull

      - name: Stop and remove existing containers
        run: |
          docker-compose down --remove-orphans

      - name: Run Docker containers
        run: docker-compose up -d

